using Microsoft.AspNetCore.Mvc;
using Spark2Scale_.Server.Models;
using System;
using System.Collections.Generic; // Required for Dictionary
using System.Linq;
using System.Threading.Tasks;

namespace Spark2Scale_.Server.Controllers
{
    [ApiController]
    [Route("api/[controller]")]
    public class StartupsController : ControllerBase
    {
        private readonly Supabase.Client _supabase;

        public StartupsController(Supabase.Client supabase)
        {
            _supabase = supabase;
        }

        [HttpPost("add")]
        public async Task<IActionResult> AddStartup([FromBody] StartupInsertDto input)
        {
            if (input == null || string.IsNullOrEmpty(input.startupname))
                return BadRequest("Startup Name is required.");

            // Map Input -> DB Model
            var newStartup = new Startup
            {
                // Sid is generated by DB or Guid.NewGuid() if needed
                StartupName = input.startupname,
                Field = input.field,
                IdeaDescription = input.idea_description,
                FounderId = input.founder_id,
                CreatedAt = DateTime.UtcNow
            };

            var result = await _supabase.From<Startup>().Insert(newStartup);
            var inserted = result.Models.FirstOrDefault();

            if (inserted == null) return StatusCode(500, "Failed to insert startup");

            // Map DB Model -> Output
            var response = new StartupResponseDto
            {
                sid = inserted.Sid,
                startupname = inserted.StartupName,
                field = inserted.Field,
                idea_description = inserted.IdeaDescription,
                founder_id = inserted.FounderId,
                created_at = inserted.CreatedAt
            };

            return Ok(response);
        }


        // GET: api/startups
        [HttpGet]
        public async Task<IActionResult> GetStartups()
        {
            var result = await _supabase.From<Startup>().Get();

            // Map Database Model -> Response DTO
            var dtos = result.Models.Select(s => new StartupResponseDto
            {
                sid = s.Sid,
                startupname = s.StartupName,
                field = s.Field,
                idea_description = s.IdeaDescription,
                founder_id = s.FounderId,
                created_at = s.CreatedAt
            }).ToList();

            return Ok(dtos);
        }

        [HttpGet("{id}")]
        public async Task<IActionResult> GetStartupById(string id)
        {
            if (!Guid.TryParse(id, out Guid sId))
                return BadRequest("Invalid ID format");

            try
            {
                var result = await _supabase.From<Startup>()
                    .Where(s => s.Sid == sId)
                    .Get();

                var startup = result.Models.FirstOrDefault();

                if (startup == null)
                    return NotFound("Startup not found");

                var response = new StartupResponseDto
                {
                    sid = startup.Sid,
                    startupname = startup.StartupName,
                    field = startup.Field,
                    idea_description = startup.IdeaDescription,
                    founder_id = startup.FounderId,
                    created_at = startup.CreatedAt
                };

                return Ok(response);
            }
            catch (Exception ex)
            {
                return StatusCode(500, $"Error: {ex.Message}");
            }
        }
        [HttpPut("update-idea/{id}")]
        public async Task<IActionResult> UpdateIdea(string id, [FromBody] IdeaUpdateDto input)
        {
            if (!Guid.TryParse(id, out Guid sId))
                return BadRequest("Invalid ID format");

            if (string.IsNullOrWhiteSpace(input.IdeaDescription))
                return BadRequest("Idea description cannot be empty");

            try
            {
                // We use RPC (Remote Procedure Call) to execute the SQL function we created.
                // This ensures the Update, Archiving, and Reset happen together safely.

                var parameters = new Dictionary<string, object>
                {
                    { "p_startup_id", sId },
                    { "p_new_idea", input.IdeaDescription }
                };

                await _supabase.Rpc("update_idea_and_reset", parameters);

                return Ok(new
                {
                    message = "Idea updated, history archived, and workflow reset successfully.",
                    idea = input.IdeaDescription
                });
            }
            catch (Exception ex)
            {
                // Log the error here if you have a logger
                return StatusCode(500, $"Error updating idea: {ex.Message}");
            }
        }
    }
}