using Microsoft.AspNetCore.Mvc;
using Spark2Scale_.Server.Models;
using System;
using System.Collections.Generic; // Required for Dictionary
using System.Linq;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using System.Text.Json;
using System.Text.Json.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System.Collections.Generic;

namespace Spark2Scale_.Server.Controllers
{
    [ApiController]
    [Route("api/[controller]")]
    public class StartupsController : ControllerBase
    {
        private readonly Supabase.Client _supabase;
        private readonly Services.AccessControlService _access;
        private readonly ILogger<StartupsController> _logger;

        public StartupsController(
            Supabase.Client supabase,
            Services.AccessControlService access,
            ILogger<StartupsController> logger)
        {
            _supabase = supabase;
            _access = access;
            _logger = logger;
        }

        public class MarketResearchRequest
        {
            public string Region { get; set; }
            public string Category { get; set; }
        }

        [HttpPost("add")]
        public async Task<IActionResult> AddStartup([FromBody] StartupInsertDto input)
        {
            // ... (keep existing login, maybe add global role check if needed)
            if (input == null || string.IsNullOrEmpty(input.startupname))
                return BadRequest("Startup Name is required.");

            // Map Input -> DB Model
            var newStartup = new Startup
            {
                // Sid is generated by DB or Guid.NewGuid() if needed
                StartupName = input.startupname,
                Field = input.field,
                IdeaDescription = input.idea_description,
                Region = input.region,
                StartupStage = input.startup_stage,
                FounderId = input.founder_id,
                CreatedAt = DateTime.UtcNow
            };

            var result = await _supabase.From<Startup>().Insert(newStartup);
            var inserted = result.Models.FirstOrDefault();

            if (inserted == null) return StatusCode(500, "Failed to insert startup");

            // Map DB Model -> Output
            var response = new StartupResponseDto
            {
                sid = inserted.Sid,
                startupname = inserted.StartupName,
                field = inserted.Field,
                idea_description = inserted.IdeaDescription,
                region = inserted.Region,
                startup_stage = inserted.StartupStage,
                founder_id = inserted.FounderId,
                created_at = inserted.CreatedAt
            };

            return Ok(response);
        }


        // GET: api/startups
        [HttpGet]
        public async Task<IActionResult> GetStartups([FromQuery] string? founderId, [FromQuery] string? contributorId)
        {
            try
            {
                // If founderId is provided, filter by it
                if (!string.IsNullOrEmpty(founderId) && Guid.TryParse(founderId, out Guid fId))
                {
                    var result = await _supabase.From<Startup>()
                        .Where(s => s.FounderId == fId)
                        .Get();

                    var dtos = result.Models.Select(s => new StartupResponseDto
                    {
                        sid = s.Sid,
                        startupname = s.StartupName,
                        field = s.Field,
                        idea_description = s.IdeaDescription,
                        region = s.Region,
                        startup_stage = s.StartupStage,
                        founder_id = s.FounderId,
                        created_at = s.CreatedAt
                    }).ToList();

                    return Ok(dtos);
                }
                // If contributorId is provided, filter by it
                else if (!string.IsNullOrEmpty(contributorId) && Guid.TryParse(contributorId, out Guid cId))
                {
                    // 1. AUTO-ACCEPT LOGIC REMOVED - Managed via InvitationController

                    // 2. FETCH STARTUPS (Existing Logic)
                    // Query the 'contributors' table directly using user_id
                    var links = await _supabase.From<Contributor>()
                       .Filter("user_id", Supabase.Postgrest.Constants.Operator.Equals, cId.ToString())
                       .Get();

                    var startupIds = links.Models
                        .Where(x => x.startup_id != null) // Ensure we don't grab nulls
                        .Select(x => x.startup_id.Value.ToString())
                        .ToList();

                    if (!startupIds.Any()) return Ok(new List<StartupResponseDto>());

                    var result = await _supabase.From<Startup>()
                       .Filter("sid", Supabase.Postgrest.Constants.Operator.In, startupIds)
                       .Get();


                    var dtos = result.Models.Select(s => new StartupResponseDto
                    {
                        sid = s.Sid,
                        startupname = s.StartupName,
                        field = s.Field,
                        idea_description = s.IdeaDescription,
                        region = s.Region,
                        startup_stage = s.StartupStage,
                        founder_id = s.FounderId,
                        created_at = s.CreatedAt
                    }).ToList();

                    return Ok(dtos);
                }
                else
                {
                    // Otherwise return all (e.g. for investors feed)
                    var result = await _supabase.From<Startup>().Get();

                    var dtos = new List<StartupResponseDto>();
                    
                    // Retrieve User ID from Token for Role Check (if available)
                    Guid? currentUserId = null;
                    var authHeader = Request.Headers["Authorization"].FirstOrDefault();
                    if (!string.IsNullOrEmpty(authHeader) && authHeader.StartsWith("Bearer "))
                    {
                        var token = authHeader.Substring("Bearer ".Length).Trim();
                        try {
                            var user = await _supabase.Auth.GetUser(token);
                            if (user != null && Guid.TryParse(user.Id, out Guid uid))
                            {
                                currentUserId = uid;
                            }
                        } catch {}
                    }

                    foreach(var s in result.Models)
                    {
                        string? role = null;
                        if (currentUserId.HasValue)
                        {
                            if (s.FounderId == currentUserId.Value) role = "Founder";
                            else 
                            {
                                // Check Contributor
                                var contrib = await _supabase.From<StartupContributor>()
                                    .Match(new Dictionary<string, string> {
                                        { "startup_id", s.Sid.ToString() },
                                        { "contributor_id", currentUserId.Value.ToString() }
                                    }).Get();
                                if (contrib.Models.Any()) role = contrib.Models.First().Role ?? "Contributor";
                            }
                        }

                        dtos.Add(new StartupResponseDto
                        {
                            sid = s.Sid,
                            startupname = s.StartupName,
                            field = s.Field,
                            idea_description = s.IdeaDescription,
                            region = s.Region,
                            startup_stage = s.StartupStage,
                            founder_id = s.FounderId,
                            created_at = s.CreatedAt,
                            current_role = role
                        });
                    }

                    return Ok(dtos);
                }
            }
            catch (Exception ex)
            {
                return StatusCode(500, $"Error fetching startups: {ex.Message}");
            }
        }

        [HttpGet("{id}")]
        public async Task<IActionResult> GetStartupById(string id)
        {
            if (!Guid.TryParse(id, out Guid sId))
                return BadRequest("Invalid ID format");

            try
            {
                var result = await _supabase.From<Startup>()
                    .Where(s => s.Sid == sId)
                    .Get();

                var startup = result.Models.FirstOrDefault();

                if (startup == null)
                    return NotFound("Startup not found");

                // Determine Role
                string? role = null;
                var authHeader = Request.Headers["Authorization"].FirstOrDefault();
                if (!string.IsNullOrEmpty(authHeader) && authHeader.StartsWith("Bearer "))
                {
                    var token = authHeader.Substring("Bearer ".Length).Trim();
                    try 
                    {
                        var user = await _supabase.Auth.GetUser(token);
                        if (user != null && Guid.TryParse(user.Id, out Guid currentUserId))
                        {
                            if (startup.FounderId == currentUserId) 
                            {
                                role = "Founder";
                            }
                            else 
                            {
                                var contrib = await _supabase.From<StartupContributor>()
                                    .Match(new Dictionary<string, string> {
                                        { "startup_id", sId.ToString() },
                                        { "contributor_id", currentUserId.ToString() }
                                    }).Get();
                                if (contrib.Models.Any()) 
                                {
                                    role = contrib.Models.First().Role ?? "Contributor";
                                }
                            }
                        }
                    }
                    catch 
                    { 
                        // Token might be invalid or expired, ignore role 
                    }
                }

                var response = new StartupResponseDto
                {
                    sid = startup.Sid,
                    startupname = startup.StartupName,
                    field = startup.Field,
                    idea_description = startup.IdeaDescription,
                    region = startup.Region,
                    startup_stage = startup.StartupStage,
                    founder_id = startup.FounderId,
                    created_at = startup.CreatedAt,
                    current_role = role
                };

                return Ok(response);
            }
            catch (Exception ex)
            {
                return StatusCode(500, $"Error: {ex.Message}");
            }
        }
        [HttpPut("update-idea/{id}")]
        public async Task<IActionResult> UpdateIdea(string id, [FromBody] IdeaUpdateDto input)
        {
            if (!Guid.TryParse(id, out Guid sId))
                return BadRequest("Invalid ID format");

            if (string.IsNullOrWhiteSpace(input.IdeaDescription))
                return BadRequest("Idea description cannot be empty");

            try
            {
                // CRITICAL: RBAC CHECK
                var token = Request.Headers["Authorization"].FirstOrDefault()?.Replace("Bearer ", "");
                
                if (string.IsNullOrEmpty(token))
                    return Unauthorized("Missing authorization token.");

                if (!await _access.IsFounderOrOwner(token, sId))
                {
                    return StatusCode(403, "Only the Founder can update the idea.");
                }

                var parameters = new Dictionary<string, object>
                {
                    { "p_startup_id", sId },
                    { "p_new_idea", input.IdeaDescription }
                };

                await _supabase.Rpc("update_idea_and_reset", parameters);

                return Ok(new
                {
                    message = "Idea updated, history archived, and workflow reset successfully.",
                    idea = input.IdeaDescription
                });
            }
            catch (Exception ex)
            {
                // Log the error here if you have a logger
                return StatusCode(500, $"Error updating idea: {ex.Message}");
            }
        }

        [HttpPost("{id}/generate-market-research")]
        public async Task<IActionResult> GenerateMarketResearch(string id, [FromBody] MarketResearchRequest request)
        {
            Console.WriteLine($"[MarketResearch] 🚀 Request received for Startup ID: {id}");

            if (!Guid.TryParse(id, out Guid sId)) return BadRequest("Invalid ID format");

            try
            {
                // 1. Get Startup Data
                var result = await _supabase.From<Startup>().Where(s => s.Sid == sId).Get();
                var startup = result.Models.FirstOrDefault();
                if (startup == null) return NotFound("Startup not found");

                string jsonContent = "";

                // ---------------------------------------------------------
                // 2. REAL API CALL (Azure AI Service)
                // ---------------------------------------------------------
                using (var client = new HttpClient())
                {
                    // Set 10-minute timeout for AI generation
                    client.Timeout = TimeSpan.FromMinutes(10);

                    var apiUrl = "https://spark2scale-ai-server.azurewebsites.net/api/v1/market-research/research";

                    Console.WriteLine($"[MarketResearch] 📡 Calling Real API: {apiUrl}");

                    var externalPayload = new
                    {
                        idea = startup.IdeaDescription ?? "No description",
                        problem = "Identify primary market pain points for " + startup.StartupName,
                        region = request.Region,
                        category = request.Category
                    };

                    var response = await client.PostAsJsonAsync(apiUrl, externalPayload);

                    if (!response.IsSuccessStatusCode)
                    {
                        var error = await response.Content.ReadAsStringAsync();
                        Console.WriteLine($"[MarketResearch] ❌ API Failed: {response.StatusCode} - {error}");
                        return StatusCode((int)response.StatusCode, $"AI Service Failed: {error}");
                    }

                    jsonContent = await response.Content.ReadAsStringAsync();
                    Console.WriteLine($"[MarketResearch] ✅ Received Data ({jsonContent.Length} bytes)");
                }

                // ---------------------------------------------------------
                // 3. PARSE JSON FOR DATABASE (The Fix)
                // ---------------------------------------------------------
                // We convert the string to a Dictionary<string, object>.
                // This ensures Supabase can save it to the 'jsonb' column without crashing.
                object jsonObjectToSave;
                try
                {
                    jsonObjectToSave = JsonConvert.DeserializeObject<Dictionary<string, object>>(jsonContent);
                }
                catch
                {
                    // Fallback: If it's an array (list), deserialize to List<object>
                    jsonObjectToSave = JsonConvert.DeserializeObject<List<object>>(jsonContent);
                }

                // ---------------------------------------------------------
                // 4. SAVE TO STORAGE (Backup File)
                // ---------------------------------------------------------
                var fileName = $"{sId}/market_research_{DateTime.UtcNow.Ticks}.json";
                var fileBytes = System.Text.Encoding.UTF8.GetBytes(jsonContent);
                string publicUrl = "";

                try
                {
                    await _supabase.Storage.From("startup-docs").Upload(fileBytes, fileName);
                    publicUrl = _supabase.Storage.From("startup-docs").GetPublicUrl(fileName);
                }
                catch (Exception ex)
                {
                    Console.WriteLine($"[MarketResearch] ⚠️ Storage upload skipped: {ex.Message}");
                }

                // ---------------------------------------------------------
                // 5. SAVE TO DATABASE TABLE
                // ---------------------------------------------------------
                try
                {
                    // A. Find the currently active document
                    var existingDocs = await _supabase.From<Document>()
                        .Filter("startup_id", Supabase.Postgrest.Constants.Operator.Equals, sId.ToString())
                        .Filter("type", Supabase.Postgrest.Constants.Operator.Equals, "Market Research")
                        .Filter("is_current", Supabase.Postgrest.Constants.Operator.Equals, "true")
                        .Get();

                    var currentDoc = existingDocs.Models.FirstOrDefault();
                    int nextVersion = 1;

                    // B. Archive the old one (if exists)
                    if (currentDoc != null)
                    {
                        Console.WriteLine($"[MarketResearch] 📂 Archiving version {currentDoc.CurrentVersion}...");

                        // Mark old doc as NOT current
                        currentDoc.IsCurrent = false;
                        await _supabase.From<Document>().Update(currentDoc);

                        // Increment version for the new doc
                        nextVersion = currentDoc.CurrentVersion + 1;
                    }

                    // C. Insert the NEW document
                    Console.WriteLine($"[MarketResearch] 🆕 Saving new version {nextVersion}...");

                    var newDoc = new Document
                    {
                        StartupId = sId,
                        DocumentName = $"Market Research Analysis v{nextVersion}",
                        Type = "Market Research",
                        CurrentPath = publicUrl,
                        CurrentVersion = nextVersion,
                        CanAccess = 1, // 1 = Private/Team only, change logic if needed
                        UpdatedAt = DateTime.UtcNow,
                        CreatedAt = DateTime.UtcNow,
                        IsCurrent = true, // This is now the active one
                        JsonResponse = jsonObjectToSave // Saving Dictionary
                    };

                    await _supabase.From<Document>().Insert(newDoc);
                }
                catch (Exception dbEx)
                {
                    Console.WriteLine($"[MarketResearch] ❌ DATABASE SAVE FAILED: {dbEx.Message}");
                    return StatusCode(500, new { error = "Database Save Failed", details = dbEx.Message });
                }

                Console.WriteLine("[MarketResearch] 🎉 SUCCESS: New version saved.");

                // Return raw JSON so frontend parses it automatically as an object
                return Content(jsonContent, "application/json");
            }
            catch (Exception ex)
            {
                Console.WriteLine($"[MarketResearch] 💥 CRITICAL ERROR: {ex.Message}");
                return StatusCode(500, new { error = "Internal Server Error", message = ex.Message });
            }
        }
    }

}