"use client";

/**
 * RecommendationCard.tsx
 * -----------------------
 * Reusable rectangular card for a single recommendation report.
 * Each generation replaces the previous one — no versioning displayed.
 *
 * Layout
 * ─────────────────────────────────────────────────────────────────
 *   ┌────────────────────────────────────────────────────────────┐
 *   │  📄  Recommendations              [View]  [Download PDF]  │
 *   │      Generated 19 Feb 2026 · Pre-Seed                     │
 *   └────────────────────────────────────────────────────────────┘
 *
 * PDF export uses jsPDF text-layout (no html2canvas) so it is
 * immune to the "unsupported color function lab/oklch" crash that
 * html2canvas throws when parsing modern Tailwind / Radix CSS.
 */

import React, { useState } from "react";
import { Eye, Download, Loader2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import {
    Dialog,
    DialogContent,
    DialogHeader,
    DialogTitle,
    DialogTrigger,
} from "@/components/ui/dialog";
import jsPDF from "jspdf";
import { DBRecommendation, RecommendationContent } from "@/services/recommendationService";
import { InvestmentMemoView, buildReportMarkdown } from "./ReportView";

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/**
 * safeParseContent
 * ----------------
 * Normalises whatever the DB hands back for the `content` JSONB column into
 * a plain JS object so that buildReportMarkdown can find `recommendation_report`.
 *
 * Edge-cases handled:
 *  1. Already a plain object  → return as-is
 *  2. JSON string             → parse once
 *  3. Double-encoded string   → parse twice  (can happen when the Postgrest
 *                                              library serialises JsonElement as a
 *                                              string instead of raw JSON)
 */
function safeParseContent(raw: any): RecommendationContent | any {
    if (!raw) return {};

    // Unwrap strings – handles both single and double encoding
    let value = raw;
    for (let i = 0; i < 2; i++) {
        if (typeof value !== "string") break;
        try { value = JSON.parse(value); } catch { return {}; }
    }

    if (typeof value !== "object" || value === null) return {};

    // Debug: log which keys arrived so it's easy to spot field-name mismatches
    if (process.env.NODE_ENV !== "production") {
        console.debug("[RecommendationCard] content keys:", Object.keys(value));
    }

    return value;
}

function formatDate(dateStr: string): string {
    if (!dateStr) return "—";
    try {
        return new Date(dateStr).toLocaleDateString("en-GB", {
            day: "numeric", month: "short", year: "numeric",
        });
    } catch {
        return dateStr;
    }
}

// ---------------------------------------------------------------------------
// PDF export — jsPDF text-only (no html2canvas, no CSS parsing)
// ---------------------------------------------------------------------------

/**
 * Converts the markdown recommendation report to a downloadable PDF using
 * jsPDF's native text-layout API.  This approach is 100% immune to the
 * html2canvas "unsupported color function lab/oklch" crash because it never
 * touches the DOM or any CSS at all.
 */
function exportToPDF(contentData: any, filename: string): void {
    const md = buildReportMarkdown(contentData);

    const pdf      = new jsPDF({ orientation: "portrait", unit: "pt", format: "a4" });
    const pageW    = pdf.internal.pageSize.getWidth();
    const pageH    = pdf.internal.pageSize.getHeight();
    const margin   = 60;
    const maxW     = pageW - margin * 2;
    const BRAND    = [87, 98, 56]  as [number, number, number];  // #576238
    const DARK     = [30, 30, 30]  as [number, number, number];
    const GREY     = [100, 100, 100] as [number, number, number];

    let y = margin;

    const newPage = () => { pdf.addPage(); y = margin; };
    const check   = (need: number) => { if (y + need > pageH - margin) newPage(); };

    // ── Cover header ──────────────────────────────────────────────────────
    pdf.setFontSize(20);
    pdf.setFont("helvetica", "bold");
    pdf.setTextColor(...BRAND);
    pdf.text("Strategic Analysis & Recommendations", margin, y);
    y += 28;

    pdf.setFontSize(9);
    pdf.setFont("helvetica", "normal");
    pdf.setTextColor(...GREY);
    pdf.text(
        `Generated by Spark2Scale Recommendation Agent  ·  ${new Date().toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" })}`,
        margin, y,
    );
    y += 6;

    pdf.setDrawColor(0);
    pdf.setLineWidth(1.5);
    pdf.line(margin, y, pageW - margin, y);
    y += 20;

    // ── Markdown body ─────────────────────────────────────────────────────
    const lines = md.split("\n");

    for (const line of lines) {
        const trimmed = line.trim();

        // blank line → small gap
        if (!trimmed) { y += 8; continue; }

        // horizontal rule
        if (trimmed.startsWith("---")) {
            check(20);
            pdf.setDrawColor(...DARK);
            pdf.setLineWidth(0.5);
            pdf.line(margin, y, pageW - margin, y);
            y += 14;
            continue;
        }

        // H2 (##)
        if (/^##\s/.test(trimmed)) {
            const text = trimmed.replace(/^##\s+/, "").replace(/\*\*/g, "");
            check(36);
            pdf.setFontSize(15);
            pdf.setFont("helvetica", "bold");
            pdf.setTextColor(...BRAND);
            const wrapped = pdf.splitTextToSize(text.toUpperCase(), maxW);
            pdf.text(wrapped, margin, y);
            y += wrapped.length * 20 + 4;
            pdf.setDrawColor(...BRAND);
            pdf.setLineWidth(0.5);
            pdf.line(margin, y, pageW - margin, y);
            y += 10;
            continue;
        }

        // H3 (###)
        if (/^###\s/.test(trimmed)) {
            const text = trimmed.replace(/^###\s+/, "").replace(/\*\*/g, "");
            check(30);
            pdf.setFontSize(12);
            pdf.setFont("helvetica", "bold");
            pdf.setTextColor(...BRAND);
            const wrapped = pdf.splitTextToSize(text.toUpperCase(), maxW);
            pdf.text(wrapped, margin, y);
            y += wrapped.length * 16 + 6;
            continue;
        }

        // H4 (####)
        if (/^####\s/.test(trimmed)) {
            const text = trimmed.replace(/^####\s+/, "").replace(/\*\*/g, "");
            check(22);
            pdf.setFontSize(11);
            pdf.setFont("helvetica", "bold");
            pdf.setTextColor(...DARK);
            const wrapped = pdf.splitTextToSize(text, maxW);
            pdf.text(wrapped, margin, y);
            y += wrapped.length * 14 + 4;
            continue;
        }

        // bullet (*, -)
        if (/^[*-]\s/.test(trimmed)) {
            const text = trimmed.substring(2).replace(/\*\*/g, "").replace(/_/g, "");
            pdf.setFontSize(10);
            pdf.setFont("helvetica", "normal");
            pdf.setTextColor(...DARK);
            const wrapped = pdf.splitTextToSize(`•  ${text}`, maxW - 12);
            check(wrapped.length * 13 + 4);
            pdf.text(wrapped, margin + 8, y);
            y += wrapped.length * 13 + 4;
            continue;
        }

        // normal paragraph
        const text = trimmed.replace(/\*\*/g, "").replace(/_/g, "");
        pdf.setFontSize(10);
        pdf.setFont("helvetica", "normal");
        pdf.setTextColor(...DARK);
        const wrapped = pdf.splitTextToSize(text, maxW);
        check(wrapped.length * 13 + 4);
        pdf.text(wrapped, margin, y);
        y += wrapped.length * 13 + 4;
    }

    // ── Page numbers ──────────────────────────────────────────────────────
    const total = (pdf.internal as any).getNumberOfPages();
    for (let i = 1; i <= total; i++) {
        pdf.setPage(i);
        pdf.setFontSize(8);
        pdf.setTextColor(...GREY);
        pdf.text(`Page ${i} of ${total}`, pageW / 2, pageH - 20, { align: "center" });
    }

    pdf.save(filename);
}

// ---------------------------------------------------------------------------
// RecommendationCard
// ---------------------------------------------------------------------------

export interface RecommendationCardProps {
    recommendation: DBRecommendation;
    startupId: string;
    /** Optional: let the parent handle PDF export (e.g. to share a loading state). */
    onDownloadPDF?: (rec: DBRecommendation) => Promise<void>;
}

export const RecommendationCard: React.FC<RecommendationCardProps> = ({
    recommendation,
    startupId,
    onDownloadPDF,
}) => {
    const [isPDFLoading, setIsPDFLoading] = useState(false);

    const contentData = safeParseContent(
        recommendation.Content ?? (recommendation as any).content
    );

    const createdAt = recommendation.CreatedAt ?? (recommendation as any).created_at ?? "";
    const stage     = contentData?.stage ?? contentData?.insights?.stage ?? "";

    // -----------------------------------------------------------------------
    // PDF download
    // -----------------------------------------------------------------------
    const handleDownload = async () => {
        if (onDownloadPDF) { await onDownloadPDF(recommendation); return; }
        setIsPDFLoading(true);
        try {
            exportToPDF(contentData, `Spark2Scale_Recommendation_${startupId}.pdf`);
        } catch (err) {
            console.error("PDF export failed:", err);
            alert("Failed to generate PDF. Please try again.");
        } finally {
            setIsPDFLoading(false);
        }
    };

    // -----------------------------------------------------------------------
    // Render
    // -----------------------------------------------------------------------
    return (
        <div className="flex items-center justify-between gap-4 rounded-xl border border-[#576238]/40 bg-white px-6 py-5 shadow-sm ring-1 ring-[#576238]/10 transition-shadow hover:shadow-md">

            {/* Left: icon + metadata */}
            <div className="flex items-start gap-4 min-w-0">
                <div className="shrink-0 rounded-lg bg-[#576238]/10 p-3">
                    {/* File-text icon */}
                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none"
                        stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"
                        className="h-5 w-5 text-[#576238]">
                        <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z" />
                        <polyline points="14 2 14 8 20 8" />
                        <line x1="16" y1="13" x2="8" y2="13" />
                        <line x1="16" y1="17" x2="8" y2="17" />
                        <polyline points="10 9 9 9 8 9" />
                    </svg>
                </div>

                <div className="min-w-0">
                    <h3 className="text-sm font-semibold text-gray-900">
                        Recommendations
                    </h3>
                    <p className="mt-0.5 text-xs text-gray-500">
                        Generated {formatDate(createdAt)}
                        {stage ? ` · ${stage}` : ""}
                    </p>
                </div>
            </div>

            {/* Right: action buttons */}
            <div className="flex items-center gap-2 shrink-0">
                {/* View */}
                <Dialog>
                    <DialogTrigger asChild>
                        <Button
                            variant="outline"
                            size="sm"
                            className="border-[#576238] text-[#576238] hover:bg-[#576238]/5 gap-1.5"
                        >
                            <Eye className="h-4 w-4" />
                            View
                        </Button>
                    </DialogTrigger>

                    <DialogContent className="max-w-[90vw] h-[90vh] overflow-y-auto p-0 bg-[#F4F1EA]">
                        <DialogHeader className="sr-only">
                            <DialogTitle>Recommendations</DialogTitle>
                        </DialogHeader>
                        <div className="py-8">
                            <InvestmentMemoView data={contentData} />
                        </div>
                    </DialogContent>
                </Dialog>

                {/* Download PDF */}
                <Button
                    variant="outline"
                    size="sm"
                    className="border-[#576238] text-[#576238] hover:bg-[#576238]/5 gap-1.5"
                    onClick={handleDownload}
                    disabled={isPDFLoading}
                >
                    {isPDFLoading
                        ? <Loader2 className="h-4 w-4 animate-spin" />
                        : <Download className="h-4 w-4" />}
                    Download PDF
                </Button>
            </div>
        </div>
    );
};

export default RecommendationCard;
