using Supabase.Postgrest.Attributes;
using Supabase.Postgrest.Models;
using System;

namespace Spark2Scale_.Server.Models
{
    // INTERNAL MODEL: Maps to Supabase Table 'document_versions'
    [Table("document_versions")]
    public class DocumentVersion : BaseModel
    {
        // Primary Key is auto-generated by DB (gen_random_uuid), so false
        [PrimaryKey("version_id", false)]
        public Guid VersionId { get; set; }

        [Column("master_id")]
        public Guid MasterId { get; set; }

        [Column("version_number")]
        public int VersionNumber { get; set; }

        [Column("generated_by")]
        public string GeneratedBy { get; set; } = "manual"; // Default

        [Column("document_name")]
        public string DocumentName { get; set; } = string.Empty;

        [Column("type")]
        public string? Type { get; set; }

        [Column("path")]
        public string? Path { get; set; }

        [Column("created_at")]
        public DateTime CreatedAt { get; set; }
    }

    // INPUT DTO: Clean input for Swagger
    public class DocumentVersionInsertDto
    {
        public Guid master_id { get; set; }
        public int version_number { get; set; }
        public string document_name { get; set; }
        public string? generated_by { get; set; } // Optional (defaults to manual)
        public string? type { get; set; }
        public string? path { get; set; }
    }

    // OUTPUT DTO: What you receive back
    public class DocumentVersionResponseDto
    {
        public Guid version_id { get; set; }
        public Guid master_id { get; set; }
        public int version_number { get; set; }
        public string generated_by { get; set; }
        public string document_name { get; set; }
        public string? type { get; set; }
        public string? path { get; set; }
        public DateTime created_at { get; set; }
    }
}